[window]
title = "Terminal"

[window.dimensions]
columns = 80
lines = 25

[font]
size = 10.0

[font.normal]
family = "DejaVu Sans Mono"

[colors.primary]
background = "#101331"   # very dark navy blue
foreground = "#f8f8f2"   # near-white (main text)

[colors.normal]
black   = "#1e2030"
red     = "#ff757f"
green   = "#c3e88d"
yellow  = "#ffc777"
blue    = "#82aaff"
magenta = "#c099ff"
cyan    = "#86e1fc"
white   = "#c8d3f5"

[colors.bright]
black   = "#444a73"
red     = "#ff757f"
green   = "#c3e88d"
yellow  = "#ffc777"
blue    = "#82aaff"
magenta = "#c099ff"
cyan    = "#86e1fc"
white   = "#c8d3f5"
